"use client";

import { Header } from "@/components/header/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GeneralProvider } from "../context/generalContext";
import { useEffect } from "react";
import { useAuthentication } from "@/hooks/auth/useAuthentication.hook";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <GeneralProvider>
      <MainComponentWithContext>{children}</MainComponentWithContext>
    </GeneralProvider>
  );
}

function MainComponentWithContext({ children }: { children: React.ReactNode }) {
  const { loginUser } = useAuthentication();
  useEffect(() => {
    loginUser();
  }, []);
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
          integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
      <body className={`${inter.className}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
